# Generated by Django 3.2.16 on 2023-02-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Edited"),
        ),
    ]
