# Generated by Django 3.2.16 on 2023-02-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_news_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseteachers",
            name="day_birth",
            field=models.DateField(verbose_name="Birth date"),
        ),
    ]
